version: 2.1

jobs:
  build: # name of your job
    macos: # executor type
      xcode: 14.2.0

    steps:
      # Commands run in a macOS virtual machine environment
      # with Xcode 14.2.0 installed
      - run: xcodebuild -version
workflows:
  hello:
    jobs:
      - build
       